## Introduction

In the last section, we have learned about the ***Maps*** helps us to transform data in a DataFrame or Series one value at a time for an entire column.

Now further more, we might want to group our data and have some specific actions to the data in it.

These are some of the functions from this section:
 - `groupby()`
 - `apply()`
 - `agg()`
 - `sort_values()`
 - `sort_index()`

and others......

Before getting into it, we must not forget our agendas: &nbsp; setting some display option, import library, and read our data file....

In [24]:
import pandas as pd
pd.set_option('display.max_row', 5)

reviews = pd.read_csv('winemag-data-130k-v2.csv')
reviews

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

`groupby()` helps you ***group similar rows based on the values in a specific column (or columns)*** and apply a function like (`sum()`, `mean()`, `count()`, etc.) to summarize the data.

There are four types of examples about the use cases of `groupby()`:
1. Group by a Single Column
2. Group by Multiple Columns
3. Applying different aggregations : &nbsp; `.agg()`
4. Reset Index for Better Readibility : &nbsp; `.reset_index()`

In [25]:
# Grouping
reviews.groupby('points').points.count() # Groupby the column 'points', and calculate how many times it appeared

points
80     397
81     692
      ...
99      33
100     19
Name: points, Length: 21, dtype: int64

This said: *"Hey, please help me to create a Series by grouping the rows based on the `points` column and counting how many times each unique `points` value appears."*

The code upon is similar to the `value_counts()` as we learn before from the ***Summary function*** section.

By default, the `groupby()` function will sort the index in ***ascending order***, to disable it just simply add `sort = False` behind.

In [26]:
reviews.points.value_counts()

points
88     17207
87     16933
       ...
99        33
100       19
Name: count, Length: 21, dtype: int64

If we would like to group the data with the minimum prices:

In [27]:
reviews.groupby('points').price.min()

points
80      5.0
81      5.0
       ...
99     44.0
100    80.0
Name: price, Length: 21, dtype: float64

Of course, we could group by ***multiple columns***, the more we add, the more details:

In [28]:
reviews.groupby(['points', 'country']).price.min()

points  country
80      Argentina      5.0
        Australia     12.0
                     ...
100     Portugal     450.0
        US            80.0
Name: price, Length: 463, dtype: float64

In [29]:
reviews.groupby(['points', 'country', 'variety']).price.max()

points  country    variety
80      Argentina  Bonarda                14.0
                   Cabernet Sauvignon     22.0
                                         ...
100     US         Cabernet Sauvignon    200.0
                   Syrah                  80.0
Name: price, Length: 7659, dtype: float64

Using the `apply()` method, we could manipulate data in any way neeed.

For example, selecting the name of the first wine reviewed from each winery in the dataset :

In [30]:
reviews.groupby('winery').apply(lambda df: df.title.iloc[0]) # groupby the category 'winery', then in each type of winery, shows the first row of it

C:\Users\liewm\AppData\Local\Temp\ipykernel_18732\4170706718.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  reviews.groupby('winery').apply(lambda df: df.title.iloc[0]) # groupby the category 'winery', then in each type of winery, shows the first row of it

winery
1+1=3                          1+1=3 NV Rosé Sparkling (Cava)
10 Knots                 10 Knots 2010 Viognier (Paso Robles)
                                  ...
àMaurice    àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                         Štoka 2009 Izbrani Teran (Kras)
Length: 16757, dtype: object

Since in the dataset contains same winery but with various title. At here, we just select the first title among the same winey category.

Let's look into another example with more complicated.

For an example, we would like to learn details about the highest point of a winery within a province inside a country:

In [31]:
reviews.groupby(['country', 'province']).apply(lambda x: x.loc[x.points.idxmax()])

C:\Users\liewm\AppData\Local\Temp\ipykernel_18732\4088109455.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  reviews.groupby(['country', 'province']).apply(lambda x: x.loc[x.points.idxmax()])

                            Unnamed: 0    country  \
country   province
Argentina Mendoza Province       82754  Argentina
          Other                  78303  Argentina
...                                ...        ...
Uruguay   San Jose               39898    Uruguay
          Uruguay                39361    Uruguay

                                                                  description  \
country   province
Argentina Mendoza Province  If the color doesn't tell the full story, the ...
          Other             Take note, this could be the best wine Colomé ...
...                                                                       ...
Uruguay   San Jose          Baked, sweet, heavy aromas turn earthy with ti...
          Uruguay           Cherry and berry aromas are ripe, healthy and ...

                                          designation  points  price  \
country   province
Argentina Mendoza Province           Nicasia Vineyard      97  120.0
          Other                               Reserva      95   90.0
...                                               ...     ...    ...
Uruguay   San Jose           El Preciado Gran Reserva      87   50.0
          Uruguay           Blend 002 Limited Edition      91   22.0

                                    province region_1 region_2  \
country   province
Argentina Mendoza Province  Mendoza Province  Mendoza      NaN
          Other                        Other    Salta      NaN
...                                      ...      ...      ...
Uruguay   San Jose                  San Jose      NaN      NaN
          Uruguay                    Uruguay      NaN      NaN

                                  taster_name taster_twitter_handle  \
country   province
Argentina Mendoza Province  Michael Schachner           @wineschach
          Other             Michael Schachner           @wineschach
...                                       ...                   ...
Uruguay   San Jose          Michael Schachner           @wineschach
          Uruguay           Michael Schachner           @wineschach

                                                                        title  \
country   province
Argentina Mendoza Province  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
          Other                            Colomé 2010 Reserva Malbec (Salta)
...                                                                       ...
Uruguay   San Jose          Castillo Viejo 2005 El Preciado Gran Reserva R...
          Uruguay           Narbona NV Blend 002 Limited Edition Tannat-Ca...

                                          variety                winery
country   province
Argentina Mendoza Province                 Malbec  Bodega Catena Zapata
          Other                            Malbec                Colomé
...                                           ...                   ...
Uruguay   San Jose                      Red Blend        Castillo Viejo
          Uruguay           Tannat-Cabernet Franc               Narbona

[425 rows x 14 columns]

Besides the function `.apply()` , there's another function works well with the `groupby()` function: &nbsp; `.agg()`

The aggregation function (`.agg()`) summarize the data (The previous section about the summary):
- `sum()`
- `mean()`
- `max()`
- `min()`
- `count()`
- `std()`
- .....

Let's say we would like to summarize out the len, min, and max of the price's data and groupby country:

In [32]:
reviews.groupby('country').price.agg([len, min, max])

C:\Users\liewm\AppData\Local\Temp\ipykernel_18732\2654178195.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  reviews.groupby('country').price.agg([len, min, max])
C:\Users\liewm\AppData\Local\Temp\ipykernel_18732\2654178195.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  reviews.groupby('country').price.agg([len, min, max])

            len   min    max
country
Argentina  3800   4.0  230.0
Armenia       2  14.0   15.0
...         ...   ...    ...
Ukraine      14   6.0   13.0
Uruguay     109  10.0  130.0

[43 rows x 3 columns]

In [33]:
country_reviewed = reviews.groupby(['country', 'province']).description.agg([len])
country_reviewed

                             len
country   province
Argentina Mendoza Province  3264
          Other              536
...                          ...
Uruguay   San Jose             3
          Uruguay             24

[425 rows x 1 columns]

In [34]:
mi = country_reviewed.index
type(mi)

pandas.core.indexes.multi.MultiIndex

After using the `groupby()` function, the grouped column becomes the indes (in this example: ***country & province***). &nbsp; To restore it as a normal column, use `reset_index()`:

In [43]:
country_reviewed.reset_index()

     index    country          province   len
0        0  Argentina  Mendoza Province  3264
1        1  Argentina             Other   536
..     ...        ...               ...   ...
423    423    Uruguay          San Jose     3
424    424    Uruguay           Uruguay    24

[425 rows x 4 columns]

In a nutshell, the `groupby()` function provides us a more detailed description about the data associated with the aggregation function.

In [36]:
# Sorting

## Sorting

In the groupby() function, we have mentioned that the default sorting is ascending in the index order. From this section,  we would learn to sort the data frame with our desired.
1. `sort_values()`
2. `sort_index()`

In [37]:
country_reviewed

                             len
country   province
Argentina Mendoza Province  3264
          Other              536
...                          ...
Uruguay   San Jose             3
          Uruguay             24

[425 rows x 1 columns]

In [38]:
country_reviewed = country_reviewed.reset_index()
country_reviewed.sort_values('len')

    country               province    len
179  Greece  Muscat of Kefallonian      1
192  Greece          Sterea Ellada      1
..      ...                    ...    ...
415      US             Washington   8639
392      US             California  36247

[425 rows x 3 columns]

To sort from largest to smallest, set `ascending = False`

In [39]:
country_reviewed.sort_values('len', ascending = False)

    country    province    len
392      US  California  36247
415      US  Washington   8639
..      ...         ...    ...
63    Chile     Coelemu      1
149  Greece      Beotia      1

[425 rows x 3 columns]

If we want to sort rows based on the index instead of the values, use `sort_index()`

In [40]:
country_reviewed.sort_index()

       country          province   len
0    Argentina  Mendoza Province  3264
1    Argentina             Other   536
..         ...               ...   ...
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    24

[425 rows x 3 columns]

If we would like to sort simultaneously with two columns:

In [41]:
country_reviewed.sort_values(['country', 'len'])

       country          province   len
1    Argentina             Other   536
0    Argentina  Mendoza Province  3264
..         ...               ...   ...
424    Uruguay           Uruguay    24
419    Uruguay         Canelones    43

[425 rows x 3 columns]